/* el nombre del cliente y cuantas veces alquilo el vehiculo */

select  NOMBRE_EMPRESA, APELLIDO_CLIENTES, NOMBRES_CLIENTES, TIPO_ALQUILER,TIEMPO_ALQUILER, CANTIDA_ALQUILER
from EMPRESA, CLIENTE inner join ALQUILER
on CLIENTE.ID_CLIENTES=ALQUILER.ID_ALQUILER
where ALQUILER.CANTIDA_ALQUILER=CANTIDA_ALQUILER
group by NOMBRE_EMPRESA, APELLIDO_CLIENTES, NOMBRES_CLIENTES, TIPO_ALQUILER,TIEMPO_ALQUILER, CANTIDA_ALQUILER
order by APELLIDO_CLIENTES;

