/*cuantas veces han estado en mantenimiento los vechiculos de la institución */

select  NOMBRE_EMPRESA, TIPO_VEHICULO, PLACA_VEHICULO, MARCA_VEHICULO,NUMERO_MANTENIMIENTO, DIA_MANTENIMIENTO
from EMPRESA, MANTENIMIENTO inner join VEHICULO
on MANTENIMIENTO.ID_MANTENIMIENTO=VEHICULO.ID_VEHICULO
where MANTENIMIENTO.TIPO_MANTENIMIENTO=TIPO_MANTENIMIENTO
order by NUMERO_MANTENIMIENTO;
